env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2020
plugins:
  - prettier
root: true
rules:
  prettier/prettier: warn
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    parser: '@typescript-eslint/parser'
    parserOptions:
      sourceType: module
    env:
      browser: true
      commonjs: true
      node: false
    plugins:
      - react
      - react-hooks
      - '@typescript-eslint'
    extends:
      - plugin:react/recommended
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint
    rules:
      '@typescript-eslint/explicit-function-return-type': 'off'
      '@typescript-eslint/explicit-module-boundary-types': 'off'
      '@typescript-eslint/interface-name-prefix': 'off'
      '@typescript-eslint/no-explicit-any': 'off'
      '@typescript-eslint/no-unused-vars':
        - 'error'
        - argsIgnorePattern: '^_'
          varsIgnorePattern: '^_'
      '@typescript-eslint/no-use-before-define': 'off'
      '@typescript-eslint/prefer-optional-chain': warn
      '@typescript-eslint/ban-types': [
        'error',
        {
          'extendDefaults': true,
          'types': {
            '{}': false
          }
        }
      ]
      no-undef: 'off'
      react/prop-types: 'off'
      react/react-in-jsx-scope: 'off'
      react-hooks/rules-of-hooks: error
      react-hooks/exhaustive-deps: warn
    settings:
      react:
        version: detect
  - files:
      - '*.js'
    extends:
      - plugin:node/recommended
    plugins:
      - node
    rules:
      node/no-unpublished-require: 'off'
      node/no-unpublished-import: 'off'
  - files:
      - next.config.js
    env:
      commonjs: true
    parserOptions:
      sourceType: module
      ecmaFeatures:
        jsx: true
    rules:
      node/no-unsupported-features/es-syntax: [error, {
        ignores: [modules]
      }]
